version: '3.9'
services:
  web:
    container_name: prayers-connect
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: prayers-connect-db
    ports:
      - "27027:27017"